// src/ui/base/Input/index.tsx
import {JSX, Ref} from 'preact'
import {commonCss} from 'styles'
import {clsx} from 'utils/dom'
import {css} from './style'

export interface InputProps {
  ref?: Ref<HTMLInputElement>
  name?: string
  type?: 'password' | 'number' | 'email' | 'date'
  autoComplete?: HTMLInputElement['autocomplete']
  label?: string
  textarea?: boolean
  placeholder?: string
  error?: string
  value?: string
  class?: string
  onChange?: JSX.GenericEventHandler<HTMLInputElement>
  onBlur?(): void
}

export const Input = ({
  ref,
  label,
  error,
  onChange,
  class: cn,
  textarea = false,
  ...rest
}: InputProps) => {
  const Comp = textarea === true ? 'textarea' : 'input'

  return (
    <div class={clsx(css.wrapper(), cn)}>
      {label && <div class={css.label()}>{label}</div>}

      <Comp
        ref={ref as any}
        onChange={onChange as any}
        class={css.input()}
        {...rest}
      />

      {error && <div class={commonCss.error()}>{error}</div>}
    </div>
  )
}

// src/ui/base/Input/Input.vue
<script setup lang="ts">
import type {InputProps} from './style'
import {commonCss} from '../../../styles'
import {css} from './style'

const props = defineProps<InputProps>()

defineEmits<{
  (e: 'change', val: Event): void
  (e: 'blur', val: FocusEvent): void
}>()
</script>

<template>
  <div :class="[css.wrapper(), (props as any).class]">
    <div :class="css.label()">
      {{ label }}
    </div>

    <component
      :is="textarea ? 'textarea' : 'input'"
      :class="css.input()"
      :name="name"
      :type="type"
      :autocomplete="autoComplete"
      :placeholder="placeholder"
      :value="value"
      @change="(e: Event) => $emit('change', e)"
      @blur="(e: FocusEvent) => $emit('blur', e)"
    />

    <div v-if="error" :class="commonCss.error()">
      {{ error }}
    </div>
  </div>
</template>
