// src/ui/forms/FieldText/index.tsx
import {useField} from 'forms'
import {InputProps, Input} from 'ui/base'

export interface FieldTextProps extends InputProps {
  name: string
}

export const FieldText = ({name, ...inputProps}: FieldTextProps) => {
  const {error, input} = useField(name)

  return (
    <Input
      {...inputProps}
      {...input}
      error={error}
    />
  )
}

// src/ui/forms/FieldText/FieldText.vue
<script setup lang="ts">
import type {InputProps} from '../../base'
import {useField} from '../../../forms'
import {Input} from '../../base'

interface FieldTextProps extends Omit<InputProps, 'modelValue'> {
  name: string
}

const props = defineProps<FieldTextProps>()

const {error, value} = useField((props as FieldTextProps).name)
</script>

<template>
  <Input v-bind="props" v-model="value" :error="error" />
</template>
