// src/pages/Forms.vue
<script setup lang="ts">
import { useForm, Form } from '../forms';
import {FieldText} from '../ui/forms'
import {Button} from '../ui/base/Button'
import {Card} from '../ui/base/Card'

interface LoginValues {
  login: string
  password: string
}
const loginValues: LoginValues = {
  login: '',
  password: '',
}

// const loginOptions: SelectOption[] = [
//   {label: 'Email', value: 'e'},
//   {label: 'SSO', value: 'e'},
// ]

useForm<LoginValues>({
  initialValues: loginValues,
  validate(vals, errors) {
    if (!vals.login) errors.login = 'Поле обязательное'

    return errors
  },
})
</script>

<template>
  <Card>
    <Form :submit="values => console.log('values', values)">
      <FieldText name="login" label="Логин" />
      <FieldText name="password" label="Пароль" type="password" />

      <Button>Войти</Button>
    </Form>
  </Card>
</template>

// src/pages/Forms.tsx
import {useForm, Form} from 'forms'
import {SelectOption, Button, Select, Card} from 'ui/base'
import {FieldText} from 'ui/forms'

interface LoginValues {
  login: string
  password: string
}
const loginValues: LoginValues = {
  login: '',
  password: '',
}

const loginOptions: SelectOption[] = [
  {label: 'Email', value: 'e'},
  {label: 'SSO', value: 'e'},
]

const LoginForm = () => {
  const form = useForm<LoginValues>({
    initialValues: loginValues,
    validate(vals, errors) {
      if (!vals.login) errors.login = 'Поле обязательное'

      return errors
    },
  })

  return (
    <Form {...form} onSubmit={values => console.log('values', values)}>
      <FieldText name="login" label="Логин" />
      <FieldText name="password" label="Пароль" type="password" />
      <Select label="Тип входа" value={loginOptions[0]} options={loginOptions} />
      <Button>Войти</Button>
    </Form>
  )
}

export const Forms = () => (
  <Card>
    <LoginForm />
  </Card>
)
