// src/ui/complex/Sidebar/Sidebar.vue
<script setup lang="ts">
import {useRoute} from 'vue-router'
import {css} from './style'

const {links} = defineProps<{
  links: Array<{
    to?: string
    onClick?(): void
    text: string
  }>
}>()

const route = useRoute()
</script>

<template>
  <div :class="css.wrapper()">
    <template v-for="{text, onClick, to} in links" :key="to">
      <router-link
        v-if="typeof to === 'string'"
        :style="route.path === to ? 'background-color: #232324' : undefined"
        :class="css.link()"
        :to="to"
      >
        {{ text }}
      </router-link>
      <div
        v-else
        :class="css.link()"
        @click="onClick"
      >
        {{ text }}
      </div>
    </template>
  </div>
</template>

// src/ui/complex/Sidebar/index.tsx
import {css} from './style'

interface SidebarProps {
  links: Array<{
    to?: string
    onClick?(): void
    text: string
  }>
  pathname: string
  navigate(path: string): void
}

export const Sidebar = ({links, pathname, navigate}: SidebarProps) => (
  <div className={css.wrapper()}>
    {links.map(({to, text, onClick}) => {
      if (typeof to === 'string') {
        const style = pathname === to ? 'background-color: #232324;' : undefined

        return (
          <a
            style={style}
            href={to}
            className={css.link()}
            onClick={e => {
              e.preventDefault()
              navigate(to)
            }}
          >
            {text}
          </a>
        )
      }

      return (
        <div className={css.link()} onClick={onClick}>
          {text}
        </div>
      )
    })}
  </div>
)
